# example netlify.toml
[build]
  command = "vite build"
  functions = "netlify/functions"
  publish = "dist"
 
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
   Access-Control-Allow-Origin = "*"
 
 
  [[headers]]
  for = "/*"
 
  
  [headers.values]
    Access-Control-Allow-Origin = "*"